### ISSUE TITLE
Swallows too many exceptions

### ISSUE THREAD

**Issue by Odaeus** [activeadmin/inherited_resources#28]
There are some problem areas where exceptions are being silently discarded only to lead to errors further on that are hard to track down.

E.g. class_methods.rb:306 gets the resource class but rescues and returns nil if my model definition has an error, leading to an exception in the IR code later on when it calls find on nil.

There are also "rescue nil" lines in the controller methods that have caused me problems.

Will fork and try to patch in Jan, but if there are any particular reasons for these or no one else experiences this I'd be interested in hearing about it.

Thanks!

**Comment by josevalim** [comment]
Definitely an issue. I will work on that as well when I have sometime.

**Comment by josevalim** [comment]
Fixed.

**Comment by Odaeus** [comment]
H Jose, this is still a problem when the class attempts to determine the model name from the controller name, the code is still the same at:
http://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/class_methods.rb#L229

It's a much more informative error message if the begin/rescue block is removed.
Thanks,
Andrew
